-
  name: Create users
  hosts: localhost 
  tasks: 
    - user: name='{{ item.name }}' state=present uid='{{ item.uid }}' 
      loop:  
         - name: joe 
           uid: 1010         
         - name: akram 
           uid: 1010    
         - name: ahmed
           uid: 1010   
         - name: salim 
           uid: 1010      